[package]
name = "genesis-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }
native-sdk = { path = "../../../native-sdk" }

[dev-dependencies]
transaction = { path = "../../../transaction" }
radix-engine = { path = "../../../radix-engine" }
scrypto-unit = { path = "../../../scrypto-unit" }

[lib]
crate-type = ["cdylib", "lib"]
