name: CPU instructions
run-name: CPU instructions branch=${{ github.ref_name }}

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cpu-instructions:
    name: Run CPU instruction
    runs-on: ubuntu-22.04
    steps:
      - name: Download QEMU v8.0.3
        run: wget https://download.qemu.org/qemu-8.0.3.tar.xz |
             tar xvJf qemu-8.0.3.tar.xz |
             cd qemu-8.0.3 |
             ./configure |
             make
          
