name: CPU instructions
run-name: CPU instructions branch=${{ github.ref_name }}

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cpu-instructions:
    name: Run CPU instruction
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup dependencies
        run: |
             sudo apt-get update
             sudo apt-get install build-essential pkg-config ninja-build libglib2.0-dev meson qemu-user
             qemu-x86_64 --version
             qemu-x86_64 --help
      - name: Setup QEMU v8.0.3
        run: |
             cd ..
             wget -nv https://download.qemu.org/qemu-8.0.3.tar.xz
             tar xJf qemu-8.0.3.tar.xz
             cd qemu-8.0.3
             ./configure  --disable-system --enable-user --target-list=x86_64-linux-user --enable-plugins
             #make
             pwd
             cd ..
      - name: Compile QEMU plugin
        run: |
             pwd
             cd radix-engine-profiling/qemu-plugin
             pwd
             sed -i 's/^qemu_source_dir.*/qemu_source_dir=\x27\/home\/runner\/work\/radixdlt-scrypto\/qemu-8.0.3\/\x27/' ./meson.build 
             bash ./build.sh
             
          
